apiVersion: forklift.konveyor.io/v1beta1
kind: Plan
metadata:
  generation: 1
  name: es-server
  namespace: openshift-mtv
spec:
  archived: false
  description: ""
  map:
    network:
      name: es-server-network
      namespace: openshift-mtv
    storage:
      name: es-server-storage
      namespace: openshift-mtv
  provider:
    destination:
      name: host
      namespace: openshift-mtv
    source:
      name: vmware-es-server-lab
      namespace: openshift-mtv
  targetNamespace: stores-es
  vms:
  - hooks:
    - hook:
        name: es-server-hook
        namespace: openshift-mtv
      step: PostHook
    name: 5551smnpes001
  warm: false
