apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  annotations:
    forklift.konveyor.io/shared: "false"
  name: is-server
  namespace: openshift-mtv
spec:
  map:
  - destination:
      storageClass: odf-lvm-vg1
    source:
      id: datastore-1243
  provider:
    destination:
      name: host
      namespace: openshift-mtv
    source:
      name: lab-vsphere-provider
      namespace: openshift-mtv
