apiVersion: forklift.konveyor.io/v1beta1
kind: NetworkMap
metadata:
  annotations:
    forklift.konveyor.io/shared: "false"
  name: rs-server
  namespace: openshift-mtv
spec:
  map:
  - destination:
      name: vm-vlan101
      namespace: stores-rs
      type: multus      
  provider:
    destination:
      name: host
      namespace: openshift-mtv
    source:
      name: lab-vsphere-provider
      namespace: openshift-mtv
